services:
    pim_datagrid.product_grid.query.list_attributes:
        class: Pim\Bundle\DataGridBundle\Query\Sql\AttributesUseableInProductGrid
        arguments:
            - '@database_connection'
            - '%pim_datagrid_productgrid_attributes_per_page%'
